server:
  port: 9203
  servlet:
    context-path: /showtimes-service
spring:
  application:
    name: showtimes-service
  boot:
    admin:
      client:
        url: http://localhost:9020
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
